CREATE VIEW VW_GRAFICO_VENN_FARMACIAS AS
WITH 	FARM_A (CODIGO_CLIENTE) AS ( SELECT DISTINCT CODIGO_CLIENTE FROM FARMACIA_A),
		FARM_B (CODIGO_CLIENTE) AS ( SELECT DISTINCT CODIGO_CLIENTE FROM FARMACIA_B),
		FARM_C (CODIGO_CLIENTE) AS ( SELECT DISTINCT CODIGO_CLIENTE FROM FARMACIA_C),
		AUXILIAR (CODIGO_CLIENTE, FARMACIA_A_ID,FARMACIA_B_ID, FARMACIA_C_ID) AS 
			(SELECT COALESCE (FARM_A.CODIGO_CLIENTE, FARM_B.CODIGO_CLIENTE, FARM_C.CODIGO_CLIENTE) CODIGO_CLIENTE,
			FARM_A.CODIGO_CLIENTE FARMACIA_A_ID, FARM_B.CODIGO_CLIENTE FARMACIA_B_ID, FARM_C.CODIGO_CLIENTE FARMACIA_C_ID
			FROM FARM_A
			FULL OUTER JOIN FARM_B ON FARM_A.CODIGO_CLIENTE = FARM_B.CODIGO_CLIENTE
			FULL OUTER JOIN FARM_C ON COALESCE (FARM_A.CODIGO_CLIENTE, FARM_B.CODIGO_CLIENTE) = FARM_C.CODIGO_CLIENTE), 
		INTERSECCOES (CODIGO_CLIENTE, FARMACIA_A, FARMACIA_C, FARMACIA_B) AS 
			(SELECT CODIGO_CLIENTE, CASE WHEN FARMACIA_A_ID IS NOT NULL THEN 1 END FARMACIA_A, CASE WHEN FARMACIA_C_ID IS NOT NULL THEN 1 END FARMACIA_C, CASE WHEN FARMACIA_B_ID IS NOT NULL THEN 1 END FARMACIA_B
             FROM AUXILIAR)
SELECT FARMACIA_A, FARMACIA_B, FARMACIA_C, COUNT(*) AS TOTAL 
FROM INTERSECCOES 
GROUP BY FARMACIA_A, FARMACIA_B, FARMACIA_C
;